#!/bin/bash
# --------------------------- Os Detection ---------------------------
detect_os() {
    system_name=$(uname -s)
    case "${system_name}" in 
        Linux*) os=Linux;;
        Darwin*) os=macos;;
        CYGWIN*|MINGW|MSYS*) os=windows;;
        *)      os="unknown"
    esac
    echo "$os"    
}
# ---------------------------- config gen ----------------------------
generate_config() {
    local os="$1"
    local shell font domain
    case "$os" in
        windows)
            shell='{"C:/Program Files/Git/bin/bash.exe", "-i", "-l"}'
            font='wezterm.font("Ubuntu Mono")'
            domain='WSL:Ubuntu'
            ;;

        macos)
            shell='{"\/opt\/homebrew\/bin\/bash", "--login"}'
            font='wezterm.font("UbuntuMono Nerd Font'
            domain=''
            ;;

        linux)
            shell='{""\/bin\/bash", "--login}'
            font='wezterm.font("UbuntuMono Nerd Font")'
            domain=''
            ;;
        *)
            echo "unsupported Os: $os"
            exit 1
            ;;
    esac
    
cat <<EOF
local wezterm = require("wezterm")

return {
  window_close_confirmation = 'NeverPrompt',
  audible_bell = "Disabled",

  default_prog = $shell,
  default_domain = "$domain",

  color_scheme = 'Gruvbox Material (Gogh)',
  font = $font,
  font_size = 26,

  colors = {
    cursor_bg = "#928374",
    cursor_border = "#928374",
    cursor_fg = "#1d2021",
  },

  window_padding = {
    left = 40,
    right = 0,
    top = 0,
    bottom = 2,
  },

  term = "xterm-256color",
}
EOF
}
# ------------------------------- Main -------------------------------
main() {
    local os
    os="$(detect_os)"

    echo "Detected Os: $os"

    generate_config "$os"
}

main "$@"
