#!/bin/bash

set -e

if [[ -z $(command -v vim) ]]; then 
  echo " Warnging: you dont have vim."
fi


#-----Link base Dotfiles ----
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/dircolors" "$HOME/.dircolors"
ln -sf "$PWD/tmux" "$HOME/.tmux.conf"
ln -sf "$PWD/profile" "$HOME/.profile"
ln -sf "$PWD/inputrc" "$HOME/.inputrc"


mkdir -p "$HOME/.vim/autoload"
ln -sf "$PWD/vim/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/vim/plug.vim" "$HOME/.vim/autoload/plug.vim"

mkdir -p "$HOME/.config/nvim"
ln -sf "$PWD/vim/init.lua" "$HOME/.config/nvim/init.lua"


#----- Generate and place WezTerm config ----
if [[ -f "$PWD/wezterm/setup" ]]; then
    mkdir -p "$HOME/.config/wezterm"
    bash "$PWD/wezterm/setup" > "$HOME/.config/wezterm/wezterm.lua"
    echo "✅ WezTerm config generated"
fi



echo "✅ Dotfiles setup complete!"

