#!/bin/bash

set -e

ln -sf "$PWD/bashrc"  "$HOME/.bashrc"
ln -sf "$PWD/dircolors"  "$HOME/.dircolors"
ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/tmux" "$HOME/.tmux.conf"
ln -sf "$PWD/profile" "$HOME/.profile"
